name: Integrity Checker

on:
  push:
    branches:
      - main
env:
  TARGET_FOLDER: "test_folder"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if folder exists
        run: |
          if [ -d ${{ env.TARGET_FOLDER }} ]; then
              echo "Folder exists"
          else
              echo "Folder does not exist"
              exit 1
          fi

      - name: Zip the target folder
        run: |
          tar -czf target.tar.gz ${{ env.TARGET_FOLDER }}

      - name: Generate SHA256 hash
        run: |
          echo "SHA256_HASH=$(sha256sum target.tar.gz | awk '{ print $1 }')" >> $GITHUB_ENV

      - name: Get commit ID (SHA)
        run: |
          echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Print hash and commit ID (SHA)
        run: |
          echo "SHA256 hash of zipped ${{ env.TARGET_FOLDER }}: $SHA256_HASH"
          echo "Commit SHA: $COMMIT_SHA"

      # - name: Generate SHA256 hash
      #   run: |
      #     echo "SHA256_HASH=$(sha256sum ${{ env.TARGET_FOLDER }} | awk '{ print $1 }')" >> $GITHUB_ENV

      # - name: Get commit ID (SHA)
      #   run: |
      #     echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      # - name: Print hash and commit ID (SHA)
      #   run: |
      #     echo "SHA256 hash of ${{ env.TARGET_FOLDER }}: $SHA256_HASH"
      #     echo "Commit SHA: $COMMIT_SHA"
